# Generated by Django 3.0.4 on 2021-06-10 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_reviews_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('posting_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 15, 33, 44, 111357))),
            ],
        ),
    ]
