# Generated by Django 3.0.4 on 2021-06-16 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 23, 42, 41, 990218)),
        ),
        migrations.AddField(
            model_name='order',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 23, 42, 41, 991217)),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 23, 42, 41, 992217)),
        ),
        migrations.AddField(
            model_name='product',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 23, 42, 41, 991217)),
        ),
        migrations.AddField(
            model_name='reviews',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 23, 42, 41, 993216)),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 23, 42, 41, 993216)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 23, 42, 41, 989218)),
        ),
    ]
