# Generated by Django 3.2.4 on 2021-06-23 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210616_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 24, 3, 135113)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 24, 3, 136115)),
        ),
        migrations.AlterField(
            model_name='order',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 24, 3, 138114)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 24, 3, 139113)),
        ),
        migrations.AlterField(
            model_name='product',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 24, 3, 137114)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 24, 3, 141113)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 24, 3, 140114)),
        ),
    ]
