# Generated by Django 3.2.4 on 2021-06-23 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210622_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 27, 32, 406016)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 27, 32, 407016)),
        ),
        migrations.AlterField(
            model_name='order',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 27, 32, 409016)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 27, 32, 410016)),
        ),
        migrations.AlterField(
            model_name='product',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 27, 32, 408016)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 27, 32, 412016)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='posting_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 27, 32, 411016)),
        ),
    ]
